# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wbj/modbus_rtu_route

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wbj/modbus_rtu_route

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wbj/modbus_rtu_route/CMakeFiles /home/wbj/modbus_rtu_route//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wbj/modbus_rtu_route/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exe

# Build rule for target.
exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exe
.PHONY : exe

# fast build rule for target.
exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/build
.PHONY : exe/fast

src/crc.o: src/crc.c.o

.PHONY : src/crc.o

# target to build an object file
src/crc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/crc.c.o
.PHONY : src/crc.c.o

src/crc.i: src/crc.c.i

.PHONY : src/crc.i

# target to preprocess a source file
src/crc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/crc.c.i
.PHONY : src/crc.c.i

src/crc.s: src/crc.c.s

.PHONY : src/crc.s

# target to generate assembly for a file
src/crc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/crc.c.s
.PHONY : src/crc.c.s

src/daemon.o: src/daemon.c.o

.PHONY : src/daemon.o

# target to build an object file
src/daemon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/daemon.c.o
.PHONY : src/daemon.c.o

src/daemon.i: src/daemon.c.i

.PHONY : src/daemon.i

# target to preprocess a source file
src/daemon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/daemon.c.i
.PHONY : src/daemon.c.i

src/daemon.s: src/daemon.c.s

.PHONY : src/daemon.s

# target to generate assembly for a file
src/daemon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/daemon.c.s
.PHONY : src/daemon.c.s

src/error.o: src/error.c.o

.PHONY : src/error.o

# target to build an object file
src/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/error.c.o
.PHONY : src/error.c.o

src/error.i: src/error.c.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/error.c.i
.PHONY : src/error.c.i

src/error.s: src/error.c.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/error.c.s
.PHONY : src/error.c.s

src/init_daemon.o: src/init_daemon.c.o

.PHONY : src/init_daemon.o

# target to build an object file
src/init_daemon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/init_daemon.c.o
.PHONY : src/init_daemon.c.o

src/init_daemon.i: src/init_daemon.c.i

.PHONY : src/init_daemon.i

# target to preprocess a source file
src/init_daemon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/init_daemon.c.i
.PHONY : src/init_daemon.c.i

src/init_daemon.s: src/init_daemon.c.s

.PHONY : src/init_daemon.s

# target to generate assembly for a file
src/init_daemon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/init_daemon.c.s
.PHONY : src/init_daemon.c.s

src/logging.o: src/logging.c.o

.PHONY : src/logging.o

# target to build an object file
src/logging.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/logging.c.o
.PHONY : src/logging.c.o

src/logging.i: src/logging.c.i

.PHONY : src/logging.i

# target to preprocess a source file
src/logging.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/logging.c.i
.PHONY : src/logging.c.i

src/logging.s: src/logging.c.s

.PHONY : src/logging.s

# target to generate assembly for a file
src/logging.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/logging.c.s
.PHONY : src/logging.c.s

src/protocol_convert.o: src/protocol_convert.c.o

.PHONY : src/protocol_convert.o

# target to build an object file
src/protocol_convert.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/protocol_convert.c.o
.PHONY : src/protocol_convert.c.o

src/protocol_convert.i: src/protocol_convert.c.i

.PHONY : src/protocol_convert.i

# target to preprocess a source file
src/protocol_convert.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/protocol_convert.c.i
.PHONY : src/protocol_convert.c.i

src/protocol_convert.s: src/protocol_convert.c.s

.PHONY : src/protocol_convert.s

# target to generate assembly for a file
src/protocol_convert.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/protocol_convert.c.s
.PHONY : src/protocol_convert.c.s

src/sys_calls.o: src/sys_calls.c.o

.PHONY : src/sys_calls.o

# target to build an object file
src/sys_calls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/sys_calls.c.o
.PHONY : src/sys_calls.c.o

src/sys_calls.i: src/sys_calls.c.i

.PHONY : src/sys_calls.i

# target to preprocess a source file
src/sys_calls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/sys_calls.c.i
.PHONY : src/sys_calls.c.i

src/sys_calls.s: src/sys_calls.c.s

.PHONY : src/sys_calls.s

# target to generate assembly for a file
src/sys_calls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/sys_calls.c.s
.PHONY : src/sys_calls.c.s

src/tty_settings.o: src/tty_settings.c.o

.PHONY : src/tty_settings.o

# target to build an object file
src/tty_settings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/tty_settings.c.o
.PHONY : src/tty_settings.c.o

src/tty_settings.i: src/tty_settings.c.i

.PHONY : src/tty_settings.i

# target to preprocess a source file
src/tty_settings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/tty_settings.c.i
.PHONY : src/tty_settings.c.i

src/tty_settings.s: src/tty_settings.c.s

.PHONY : src/tty_settings.s

# target to generate assembly for a file
src/tty_settings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exe.dir/build.make CMakeFiles/exe.dir/src/tty_settings.c.s
.PHONY : src/tty_settings.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... exe"
	@echo "... src/crc.o"
	@echo "... src/crc.i"
	@echo "... src/crc.s"
	@echo "... src/daemon.o"
	@echo "... src/daemon.i"
	@echo "... src/daemon.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/init_daemon.o"
	@echo "... src/init_daemon.i"
	@echo "... src/init_daemon.s"
	@echo "... src/logging.o"
	@echo "... src/logging.i"
	@echo "... src/logging.s"
	@echo "... src/protocol_convert.o"
	@echo "... src/protocol_convert.i"
	@echo "... src/protocol_convert.s"
	@echo "... src/sys_calls.o"
	@echo "... src/sys_calls.i"
	@echo "... src/sys_calls.s"
	@echo "... src/tty_settings.o"
	@echo "... src/tty_settings.i"
	@echo "... src/tty_settings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

